### ISSUE TITLE
Invalid mnemonic when creating Seed

### ISSUE THREAD

**Issue by stephanmueller-nspagency** [DeFiChain-Wizard/core-library-frontend#3]
When I try to create a seed like in the given example

> `const mySeed = new Seed(mySeed, myPassword);`

I always get a Possible `Possible Unhandled Promise Rejection (id: 0): Error: Error: Invalid mnemonic`

The issue likely occurs here: https://github.com/DeFiChain-Wizard/core-library-frontend/blob/1becf0e2e886e7f63d0d9258757c093ed0dab901/src/wallet/seed.ts#L49

I'm using node v14.20.0 to start the [DeFiChainWizzard](https://github.com/DeFiChain-Wizard/defichain-wizard-frontend). Additionally a screenshot of my terminal output.

![image](https://user-images.githubusercontent.com/107240832/180447593-63d6bdaf-aabd-478c-8668-0341208dd568.png)

**Comment by Shogoki** [comment]
I believe this is the same issue, we had with the DFI Wallet, that we need to do an async initialization. 
We should also switch this to the Builder pattern.

I can fill in an PR for that, but this will (unfortunately) change the API a bit, when you create a new `Seed` object.
